import midtermquiz

obj = midtermquiz.customer_electric_bill_info

name = input("Name: ")
address = input("Address: ")
account_number = int(input("Account Number: "))
previous_bill = float(input("Previous Bill: "))
rate = input("Rate (Residential or Commercial): ")
date = input("Bill date/Meter reading date: ")
bill_period = input("Bill period: ")
due_date = input("Due date: ")
actual_consumption = float(input("Actual Consumption (Kilowatts): "))
next_meter_reading = input("Next Meter reading: ")
rate_per_kilowatts = float(input("Rate per kilowatts: "))

#Set the computation for the total amount and charges
charges = actual_consumption * rate_per_kilowatts
total_amount = previous_bill + charges

customer_billing_fee = midtermquiz.customer_billing_statement

generation = float(input("Generation: "))
transmission = float(input("Transmission: "))
system_loss = float(input("System loss: "))
distribution = float(input("Distribution (Meralco): "))
subsidies = float(input("Subsidies: "))
government_taxes = float(input("Government taxes: "))
universal_charges = float(input("Universal charges: "))
fitall = float(input("FiT-All (Renewable: "))
applied_credits = float(input("Applied credits: "))
other_charges = float(input("Other charges: "))
installment_due = float(input("Installment due: "))

if previous_bill == 0:
    previous_bill_output = print("Thank you")
else:
    previous_bill_output = print("Pleas pay")

print("Name: ", name)
print("Address: ", address)
print("")
print("=================================================================================================")
print("Elertic Bill")
print("Summary for Customer Account Number (CAN): ", account_number)
print("=================================================================================================")
print("Balance From Previous Billing")
print(previous_bill)
print(previous_bill_output)
print("=================================================================================================")
print("Current Charges: ")
print("Amount due: ", total_amount)
print("Due Date: ", due_date)
print("Total Amount Due: ", total_amount)
print("")
print("=================================================================================================")
print("Service Info: ")
print("Servince ID Number: ", account_number)
print("Rate: ", rate)
print("Contract in the name of: ", name)
print("Servince Address: ", address)
print("=================================================================================================")
print("Billing Info")
print("Bill Date: ", date)
print("Meter Reading Date: ", date)
print("Bill Period: ", bill_period)
print("Due Date: ", due_date)
print("Total KWH: ", actual_consumption)
print("Total current amount: ", total_amount)
print("Next Meter Reading: ", next_meter_reading)
print("=================================================================================================")
print("Customer Account Number: ", account_number, "\t\t\t\t\t\tDue Date: ", due_date)
print("=================================================================================================")
print("Please Pay")
print(total_amount)
print("=================================================================================================")
print("Bill Consumption Summary")
print("Remaining Balance From Previous Bill: ", previous_bill)
print("Generation: ", generation)
print("Transmission: ", transmission)
print("System Loss: ", system_loss)
print("Disbribution (Meralco): ", distribution)
print("Subsidies: ", subsidies)
print("Government Taxes: ", government_taxes)
print("Universal Charges: ", universal_charges)
print("FiT-All (Renewable): ", fitall)
print("Applied Credits: ", applied_credits)
print("Other Charges: ", other_charges)
print("Installment Due: ", installment_due)
print("=================================================================================================")
print("Total Amount Due: ", total_amount)
